---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: Rota Padrão
      responses:
        '200':
          description: Sucesso
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
