---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/articles":
    get:
      summary: list articles
      tags:
      - Article
      parameters:
      - name: page
        in: query
        required: true
        description: Number of page
        example: 1
        schema:
          type: integer
      - name: per_page
        in: query
        required: true
        description: Number Limit of page
        example: 10
        schema:
          type: integer
      responses:
        '200':
          description: successfully
servers:
- url: http://0.0.0.0:3000
  variables:
    defaultHost:
      default: http://0.0.0.0:3000
